server:
  port: 0
spring:
  application:
    name: analysis-service
  data:
    mongodb:
      database: tramways_analysis
  kafka:
    bootstrap-servers: ${KAFKA_URI:http://localhost:9092}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
