server:
  port: 0
spring:
  application:
    name: analysis-service
  data:
    mongodb:
      database: tramways_analysis

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
